### ISSUE TITLE
How can i get the data you use?

### ISSUE THREAD

**Issue by renhao1998** [harsh-ux/Sentiment-Analysis-of-Drug-Reviews#16]
Hello, i want to get the data you use in  'drive/My Drive/drugsCom_raw/drugsComTrain_raw.csv'  , can you republic this data ? thanks a lot!

**Comment by harsh-ux** [comment]
PFA the link to the dataset: [https://archive.ics.uci.edu/ml/datasets/Drug+Review+Dataset+%28Drugs.com%29](https://archive.ics.uci.edu/ml/datasets/Drug+Review+Dataset+%28Drugs.com%29)
